sudo: required
dist: trusty
language: go

install:
  - sudo add-apt-repository -y ppa:jonathonf/python-3.6
  - sudo apt-get update
  - sudo apt-get install -y capnproto python3.6 python3.6-dev
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo python3.6 get-pip.py
  - sudo -H pip3 install black isort
  - sudo -H pip3 install -r codegen/python/gentest/requirements.txt
  - go get -u github.com/jteeuwen/go-bindata/...

go:
  - 1.12

script:
  - ./build_apidocs.sh
  - make install
  - make test
  - make gogentest
  - make pygentest

after_success:
  - codecov

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      - feeltheajf:KtpBSt1d694nkztes1h4Nbn0#ci
