# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from .Animal import Animal
from .animalsid_service import AnimalsidService
from .http_client import HTTPClient


class Client:

    _base_uri = "http://localhost:5000"
    _services = ("animalsid",)

    def __init__(self, base_uri=_base_uri):
        http_client = HTTPClient(base_uri)
        self.animalsid = AnimalsidService(http_client)
        self.close = http_client.close
