# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from .Animal import Animal
from .animalsid_service import AnimalsidService
from .http_client import HTTPClient

BASE_URI = "http://localhost:5000"


class Client:
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def _get_services():
        return ("animalsid",)

    def __init__(self, base_uri=BASE_URI):
        http_client = HTTPClient(base_uri)
        self.animalsid = AnimalsidService(http_client)
        self.close = http_client.close
