# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

import os

from flask import Flask, send_file, send_from_directory

from path_api import path_api

dir_path = os.path.dirname(os.path.realpath(__file__))

app = Flask(__name__)

app.register_blueprint(path_api)


if __name__ == "__main__":
    app.run(debug=True)
