# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from .File import File
from .http_client import HTTPClient
from .tree_service import TreeService

BASE_URI = "http://localhost:5000"


class Client:
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def _get_services():
        return ("tree",)

    def __init__(self, loop, base_uri=BASE_URI):
        http_client = HTTPClient(loop, base_uri)

        self.tree = TreeService(http_client)
        self.close = http_client.close
