# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

import os

from path_if import path_if
from sanic import Sanic
from sanic.response import json

dir_path = os.path.dirname(os.path.realpath(__file__))

app = Sanic(__name__)

app.blueprint(path_if)


if __name__ == "__main__":
    app.run(debug=True, port=5000, workers=2)
